name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET}}
        AWS_REGION: 'us-east-1'
   
    - run: |
       echo 'DIAPKADBJNDN NDNJ'
       pwd
       aws s3 sync ./index.html s3://${{ secrets.AWS_BUCKET_NAME }} --delete  
       ls
        

       