name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  iamvarshith_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET}}
            AWS_REGION: 'us-east-1'
       
      - name: Deploy static site to S3 bucket
# Your bucker name
        run: aws s3 sync . s3://AWS_BUCKET_NAME --delete
