name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: cp ./index.html ${{secrets.AWS_Bucket_Name}} "/.index.html" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "index.html"
