name: Upload Websitecc

on:
  push:
    branches:
    - main
    - master

jobs:
  stage:
    runs-on: ubuntu-latest
   
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.PROD_BUCKET}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET}}
        AWS_REGION: 'us-east-1'   
       
    - run: |
        pwd
        ls
        echo ${{ github.ref }}

  deploy:
    runs-on: ubuntu-latest
   
   
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
        AWS_REGION: 'us-east-1'  
    - run: |
        pwd
        ls
        echo ${{ github.ref }}
  
